---
- hosts: localhost
  tasks:
  - name: Clean up the directory
    file: path=/tmp/k8s/jiradeploy state=absent

  - name: Create the tmp directory
    file: path=/tmp/k8s/jiradeploy state=directory

  - name: envs
    include_vars:
      file: envs.yaml
      name: envs

  - name: Render files template to /jiradeploy
    template: src={{ item }} dest=/tmp/k8s/jiradeploy/{{ item | basename }}
    with_fileglob: "{{playbook_dir}}/*.yml"
    # You can add extra conditional stuff here, example
    #when cluster_name in ["cluster1"]


  ###############################################################

  - name: Deploy Jira to K8s Cluster
    command: kubectl apply -f /tmp/k8s/jiradeploy

    # You can add extra conditional stuff here, example
    #when cluster_name in ["cluster1"]

  - name: Clean up the directory
    file: path=/tmp/k8s/jiradeploy state=absent
    tags:
    - cleanup